name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger deploy when code is pushed to the `main` branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Set the Node.js version to use, change this if needed

    - name: Install dependencies
      run: |
        npm install

    - name: Build Angular project
      run: |
        ./node_modules/.bin/ng build --configuration production --base-href="https://nikhithachowdarybalusu.github.io/portfolio3/"

    - name: Install angular-cli-ghpages
      run: |
        npm install -g angular-cli-ghpages

    - name: Set Git user for commit
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Deploy to GitHub Pages
      run: |
        ngh --dir=dist/portfolio3 --no-silent --message "Deploying new build"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token automatically used for authentication
